/**
 * Teams by sport for the favorite teams picker.
 * Each entry: { abbr, name, city }
 */
export const TEAMS_BY_SPORT = {
  nba: [
    { abbr: 'ATL', name: 'Hawks', city: 'Atlanta' },
    { abbr: 'BOS', name: 'Celtics', city: 'Boston' },
    { abbr: 'BKN', name: 'Nets', city: 'Brooklyn' },
    { abbr: 'CHA', name: 'Hornets', city: 'Charlotte' },
    { abbr: 'CHI', name: 'Bulls', city: 'Chicago' },
    { abbr: 'CLE', name: 'Cavaliers', city: 'Cleveland' },
    { abbr: 'DAL', name: 'Mavericks', city: 'Dallas' },
    { abbr: 'DEN', name: 'Nuggets', city: 'Denver' },
    { abbr: 'DET', name: 'Pistons', city: 'Detroit' },
    { abbr: 'GS', name: 'Warriors', city: 'Golden State' },
    { abbr: 'HOU', name: 'Rockets', city: 'Houston' },
    { abbr: 'IND', name: 'Pacers', city: 'Indiana' },
    { abbr: 'LAC', name: 'Clippers', city: 'LA' },
    { abbr: 'LAL', name: 'Lakers', city: 'Los Angeles' },
    { abbr: 'MEM', name: 'Grizzlies', city: 'Memphis' },
    { abbr: 'MIA', name: 'Heat', city: 'Miami' },
    { abbr: 'MIL', name: 'Bucks', city: 'Milwaukee' },
    { abbr: 'MIN', name: 'Timberwolves', city: 'Minnesota' },
    { abbr: 'NO', name: 'Pelicans', city: 'New Orleans' },
    { abbr: 'NY', name: 'Knicks', city: 'New York' },
    { abbr: 'OKC', name: 'Thunder', city: 'Oklahoma City' },
    { abbr: 'ORL', name: 'Magic', city: 'Orlando' },
    { abbr: 'PHI', name: '76ers', city: 'Philadelphia' },
    { abbr: 'PHX', name: 'Suns', city: 'Phoenix' },
    { abbr: 'POR', name: 'Trail Blazers', city: 'Portland' },
    { abbr: 'SAC', name: 'Kings', city: 'Sacramento' },
    { abbr: 'SA', name: 'Spurs', city: 'San Antonio' },
    { abbr: 'TOR', name: 'Raptors', city: 'Toronto' },
    { abbr: 'UTA', name: 'Jazz', city: 'Utah' },
    { abbr: 'WAS', name: 'Wizards', city: 'Washington' },
  ],
  mlb: [
    { abbr: 'ARI', name: 'Diamondbacks', city: 'Arizona' },
    { abbr: 'ATL', name: 'Braves', city: 'Atlanta' },
    { abbr: 'BAL', name: 'Orioles', city: 'Baltimore' },
    { abbr: 'BOS', name: 'Red Sox', city: 'Boston' },
    { abbr: 'CHC', name: 'Cubs', city: 'Chicago' },
    { abbr: 'CWS', name: 'White Sox', city: 'Chicago' },
    { abbr: 'CIN', name: 'Reds', city: 'Cincinnati' },
    { abbr: 'CLE', name: 'Guardians', city: 'Cleveland' },
    { abbr: 'COL', name: 'Rockies', city: 'Colorado' },
    { abbr: 'DET', name: 'Tigers', city: 'Detroit' },
    { abbr: 'HOU', name: 'Astros', city: 'Houston' },
    { abbr: 'KC', name: 'Royals', city: 'Kansas City' },
    { abbr: 'LAA', name: 'Angels', city: 'Los Angeles' },
    { abbr: 'LAD', name: 'Dodgers', city: 'Los Angeles' },
    { abbr: 'MIA', name: 'Marlins', city: 'Miami' },
    { abbr: 'MIL', name: 'Brewers', city: 'Milwaukee' },
    { abbr: 'MIN', name: 'Twins', city: 'Minnesota' },
    { abbr: 'NYM', name: 'Mets', city: 'New York' },
    { abbr: 'NYY', name: 'Yankees', city: 'New York' },
    { abbr: 'OAK', name: 'Athletics', city: 'Oakland' },
    { abbr: 'PHI', name: 'Phillies', city: 'Philadelphia' },
    { abbr: 'PIT', name: 'Pirates', city: 'Pittsburgh' },
    { abbr: 'SD', name: 'Padres', city: 'San Diego' },
    { abbr: 'SF', name: 'Giants', city: 'San Francisco' },
    { abbr: 'SEA', name: 'Mariners', city: 'Seattle' },
    { abbr: 'STL', name: 'Cardinals', city: 'St. Louis' },
    { abbr: 'TB', name: 'Rays', city: 'Tampa Bay' },
    { abbr: 'TEX', name: 'Rangers', city: 'Texas' },
    { abbr: 'TOR', name: 'Blue Jays', city: 'Toronto' },
    { abbr: 'WSH', name: 'Nationals', city: 'Washington' },
  ],
}
